#include "model_to_sfz.h"

#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <string>

namespace fbsampler::detail {

namespace {

void appendf(std::string& out, const char* fmt, ...)
{
    char buf[256];
    va_list args;
    va_start(args, fmt);
    std::vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    out += buf;
}

std::uint64_t toFrames(double value, SamplePositionUnit unit, double sampleRate)
{
    const double frames = unit == SamplePositionUnit::Frames
        ? value
        : value * sampleRate;
    return frames > 0.0 ? static_cast<std::uint64_t>(frames + 0.5) : 0;
}

std::string sfzPath(const std::string& path)
{
    std::string p = path;
    for (char& c : p)
        if (c == '\\')
            c = '/';
    return p;
}

} // namespace

std::string modelToSfzText(const InstrumentModel& model,
                           const std::vector<double>& regionSampleRates,
                           std::vector<Diagnostic>* diagnostics)
{
    std::string out;
    out += "// synthetic SFZ generated by fbsampler engine (v0 model-bind seam)\n";

    for (std::size_t i = 0; i < model.regions.size(); ++i) {
        const Region& r = model.regions[i];
        const double rate = i < regionSampleRates.size() ? regionSampleRates[i] : 0.0;
        const bool positionsUsable =
            r.positionUnit == SamplePositionUnit::Frames || rate > 0.0;

        if (!positionsUsable && diagnostics && (r.offset > 0.0 || r.loopEnabled)) {
            Diagnostic d;
            d.severity = Severity::Warning;
            d.code = "engine.position_unit_dropped";
            d.message = "region " + std::to_string(i)
                + ": sample rate unknown, offset/loop opcodes dropped (position unit is Seconds)";
            diagnostics->push_back(std::move(d));
        }

        out += "<region> sample=" + sfzPath(r.sampleFile) + "\n";
        appendf(out, "  lokey=%d hikey=%d lovel=%d hivel=%d pitch_keycenter=%d\n",
                r.loKey, r.hiKey, r.loVelocity, r.hiVelocity, r.rootKey);
        if (r.tuningCents != 0.0f)
            appendf(out, "  tune=%d\n",
                    static_cast<int>(std::lround(r.tuningCents)));
        if (r.gainDb != 0.0f)
            appendf(out, "  volume=%.6g\n", static_cast<double>(r.gainDb));
        if (r.pan != 0.0f)
            appendf(out, "  pan=%.6g\n", static_cast<double>(r.pan) * 100.0);
        appendf(out, "  bend_up=%d bend_down=%d\n",
                static_cast<int>(std::lround(r.bendUpCents)),
                static_cast<int>(std::lround(r.bendDownCents)));

        if (positionsUsable) {
            const double posRate = r.positionUnit == SamplePositionUnit::Seconds ? rate : 0.0;
            if (r.offset > 0.0)
                appendf(out, "  offset=%llu\n",
                        static_cast<unsigned long long>(
                            toFrames(r.offset, r.positionUnit, posRate ? posRate : 1.0)));
            if (r.loopEnabled) {
                appendf(out, "  loop_mode=loop_continuous loop_start=%llu loop_end=%llu\n",
                        static_cast<unsigned long long>(
                            toFrames(r.loopStart, r.positionUnit, posRate ? posRate : 1.0)),
                        static_cast<unsigned long long>(
                            toFrames(r.loopEnd, r.positionUnit, posRate ? posRate : 1.0)));
            }
        }

        const EnvelopeADSR& env = r.amplitudeEnvelope;
        appendf(out,
                "  ampeg_delay=%.6g ampeg_attack=%.6g ampeg_hold=%.6g"
                " ampeg_decay=%.6g ampeg_sustain=%.6g ampeg_release=%.6g\n",
                static_cast<double>(env.delaySeconds),
                static_cast<double>(env.attackSeconds),
                static_cast<double>(env.holdSeconds),
                static_cast<double>(env.decaySeconds),
                static_cast<double>(env.sustainLevel) * 100.0,
                static_cast<double>(env.releaseSeconds));

        for (const ModMatrixEntry& mod : r.modMatrix) {
            if (mod.source.kind != ModSourceKind::Cc)
                continue; // Velocity/KeyTrack: engine built-in defaults (v0 seam cap)
            const int cc = mod.source.ccNumber;
            switch (mod.target) {
            case ModTarget::Gain:
                appendf(out, "  volume_oncc%d=%.6g\n", cc,
                        static_cast<double>(mod.depth));
                break;
            case ModTarget::Pitch:
                appendf(out, "  pitch_oncc%d=%d\n", cc,
                        static_cast<int>(std::lround(mod.depth)));
                break;
            case ModTarget::Pan:
                appendf(out, "  pan_oncc%d=%.6g\n", cc,
                        static_cast<double>(mod.depth) * 100.0);
                break;
            }
        }
    }

    return out;
}

} // namespace fbsampler::detail
