// SF2 golden lowering harness (Story 2.1): clone of the Story-1.3 harness
// shape (sfz_golden_test.cpp) — fixture -> lowerSf2Preset -> validate ->
// serialize -> byte-exact compare against the checked-in snapshot.
//
// Fixtures are hand-built mini .sf2 files generated by
// tests/golden/sf2/tools/make_sf2.py (checked in, deterministic).
//
// Regenerating snapshots: FBSAMPLER_UPDATE_GOLDENS=1, run the [sf2][golden]
// tests once, inspect the diff before committing.

#include <catch2/catch_test_macros.hpp>

#include "fbsampler/serialize.h"
#include "fbsampler/sf2_frontend.h"
#include "fbsampler/validate.h"

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>

using namespace fbsampler;

namespace {

std::string readFile(const std::string& path)
{
    std::ifstream file(path, std::ios::binary);
    REQUIRE(file.is_open()); // fail loudly, not as an empty-string mismatch
    std::ostringstream ss;
    ss << file.rdbuf();
    return ss.str();
}

bool updateGoldensRequested()
{
    const char* env = std::getenv("FBSAMPLER_UPDATE_GOLDENS");
    return env != nullptr && env[0] != '\0' && env[0] != '0';
}

// The lowered model embeds the container path in every sf2:// sample URI; the
// golden fixture directory is machine-specific, so pin the snapshot on a
// stable relative form instead.
std::string stabilizePaths(std::string text, const std::string& dir)
{
    std::string normalizedDir = dir;
    std::replace(normalizedDir.begin(), normalizedDir.end(), '\\', '/');
    std::size_t pos = 0;
    while ((pos = text.find(normalizedDir, pos)) != std::string::npos)
        text.erase(pos, normalizedDir.size());
    return text;
}

void checkFixture(const std::string& name, int bank, int program)
{
    const std::string dir = std::string(FBSAMPLER_GOLDEN_DIR) + "/sf2/";
    const auto result = lowerSf2Preset(dir + name + ".sf2", bank, program);

    for (const auto& d : result.diagnostics) {
        INFO(d.code << ": " << d.message << " (" << d.location.file << ")");
        CHECK(d.severity != Severity::Error);
    }
    REQUIRE(result.model.has_value());
    REQUIRE(validate(*result.model).empty());

    const auto text = stabilizePaths(serializeModel(*result.model), dir);
    const std::string expectedPath = dir + name + ".expected.txt";

    if (updateGoldensRequested()) {
        std::ofstream out(expectedPath, std::ios::binary);
        REQUIRE(out.is_open());
        out << text;
        out.close();
        // A truncated snapshot (disk full, failed flush) must fail the run,
        // not silently corrupt the golden baseline.
        REQUIRE(out.good());
        SUCCEED("golden snapshot regenerated: " + expectedPath);
        return;
    }

    REQUIRE(text == readFile(expectedPath));
}

} // namespace

TEST_CASE("SF2 golden: single looped zone with volume envelope", "[sf2][golden]")
{
    checkFixture("basic", 0, 0);
}

TEST_CASE("SF2 golden: velocity layers, key splits, global zones and preset offsets",
          "[sf2][golden]")
{
    checkFixture("layers", 0, 1);
}

TEST_CASE("SF2 golden: linked stereo pair lowers as two panned regions", "[sf2][golden]")
{
    checkFixture("stereo", 0, 2);
}

TEST_CASE("SF3 lowering is structurally identical to its SF2 sibling", "[sf2][sf3][golden]")
{
    // Story 2.3 AC: the sf3 sibling's lowering snapshot must be IDENTICAL to
    // the sf2 fixture's, modulo the container extension inside the sample
    // reference URI (byte ranges/compression live in the container, not the
    // model). Everything else — zones, loops (frames in decoded PCM),
    // tuning, envelope, modulators — must be byte-equal.
    const std::string dir = std::string(FBSAMPLER_GOLDEN_DIR) + "/sf2/";
    const auto result = lowerSf2Preset(dir + "basic.sf3", 0, 0);
    for (const auto& d : result.diagnostics) {
        INFO(d.code << ": " << d.message);
        CHECK(d.severity != Severity::Error);
    }
    REQUIRE(result.model.has_value());
    REQUIRE(validate(*result.model).empty());

    std::string text = stabilizePaths(serializeModel(*result.model), dir);
    // Normalize the only legitimate difference: the container extension.
    std::size_t pos = 0;
    while ((pos = text.find(".sf3#", pos)) != std::string::npos)
        text.replace(pos, 5, ".sf2#");

    REQUIRE(text == readFile(dir + "basic.expected.txt"));
}

TEST_CASE("SF2 golden: unsupported generators warn and loop-until-release approximates",
          "[sf2][golden]")
{
    const std::string dir = std::string(FBSAMPLER_GOLDEN_DIR) + "/sf2/";
    const auto result = lowerSf2Preset(dir + "unsupported.sf2", 0, 3);
    REQUIRE(result.model.has_value());
    CHECK(std::any_of(result.diagnostics.begin(), result.diagnostics.end(),
                      [](const Diagnostic& d) {
                          return d.code == "sf2.generator_unsupported"
                              && d.severity == Severity::Warning;
                      }));
    CHECK(std::any_of(result.diagnostics.begin(), result.diagnostics.end(),
                      [](const Diagnostic& d) {
                          return d.code == "sf2.loop_mode_approximated"
                              && d.severity == Severity::Warning;
                      }));

    checkFixture("unsupported", 0, 3);
}
